### ISSUE TITLE
Please install numpy first

### ISSUE THREAD

**Issue by toshi-k** [Kaggle/docker-python#164] opened 2018-01-13 06:50 UTC
Running current environment, pyfasttext raise below error.
`Traceback (most recent call last):
  File "__init__.pxd", line 987, in numpy.import_array (src/pyfasttext.cpp:15915)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa`

In dockerfile, new contributions are written line 234-370.
https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L234-L378

However, numpy (which is basic array library for python), is called at line 383.
https://github.com/Kaggle/docker-python/blob/master/Dockerfile#L383.

In my opiniton, the cause of this errors is installing order. Generary speaking, basic library should be installed first. I think many type of libraries which have depandancy with numpy have troubles now.

Since this problem is outside of contribution area (line 234-370), I want Kaggle Team to handle it.

**Comment by toshi-k** [comment] 2018-01-13 07:41
I make a example which reproduce this error in Kaggle Kernel. Please check with this.
https://www.kaggle.com/toshik/import-pyfasttext/log

**Comment by nerdcha** [comment] 2018-01-15 04:51
Thanks for calling this out. The numpy re-install was because we were being affected by https://github.com/ContinuumIO/anaconda-issues/issues/720. That seems to have been fixed in anaconda3:5.0.1, so we've reverted to their numpy and scipy installations. Pyfasttext should now be working; I've added it to our build test script so we don't get a regression. Thanks again!

**Closed by nerdcha** 2018-01-15 04:51 UTC

**Comment by toshi-k** [comment] 2018-01-15 12:57
Thank you for the update ! I comfirm that I can import Pyfasttext successfully.
https://www.kaggle.com/toshik/import-pyfasttext/code
