### ISSUE TITLE
Build doesn't work for absolutely clean new machine

### ISSUE THREAD

**Issue by oduvan** [Kaggle/docker-python#207] opened 2018-05-02 07:54 UTC
```
Traceback (most recent call last):
  File "/opt/conda/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/conda/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_asid
e
    f(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initializ
e_master_working_set
    dist.activate(replace=False)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_na
mespace
    _handle_ns(packageName, path_item)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_m
od_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by sebbov** [comment] 2018-05-02 14:51
Thanks for reporting this.  I have confirmed that we're seeing the same issue (on the `cuda` branch, but I suppose it's the same on `master`, given what follows).

The build of this image is known to break every now and then due to its complexity and goals:  We're trying to include as much as is relevant to data scientists, and keep all that (by design) to the most recent version (often head, because doing otherwise would require pinning to a specific version).  IOW, the build is not reproducible and breakages can be introduced without any changes to this build specification.

I'll take a look at this issue, but feel free to also do so as well and send a PR if you find a fix.

**Comment by oduvan** [comment] 2018-05-02 15:08
Thanks for response.

How fresh the version on http://hub.docker.com/ ?

**Comment by sebbov** [comment] 2018-05-02 17:25
Should be 2 to 3 days ago, right before this issue popped up.

**Comment by oduvan** [comment] 2018-05-02 17:30
cool, thank you

**Comment by crawforc3** [comment] 2018-05-18 18:32
@oduvan this shouldn't be an issue now so I am going to close this. Feel free to reopen if the problem shows up again.

**Closed by crawforc3** 2018-05-18 18:32 UTC
