### ISSUE TITLE
Keep Kaggle Environment's Up-To-Date

### ISSUE THREAD

**Issue by darien-schettler** [Kaggle/docker-python#1181] opened 2022-08-02 14:29 UTC
## 🐛 Bug

**Please keep the environment up to date.** 

This is a cross-post from the Kaggle discussion topic I created [**here**](https://github.com/Kaggle/docker-python/issues/1181)

As Kaggle is primarily a data science competition platform with access to thousands of datasets, a lot of its value comes from being able to use it as an IDE with a preconfigured environment. Pretty much Google Colab but with instant access to datasets.

It's completely unacceptable that:
* **We are using a CUDA image that is 2+ years old.**
* We are using a version of Tensorflow (a Google product) that is 3 major versions behind the stable core.
* Tons of other things (old libraries galore, JAX doesn't work, etc.)

As this represents one of the primary value propositions of Kaggle as a whole, I would hope that something like this would be seen as a priority. It's pretty clear from the lack of movement that this isn't the case. 

Are we just out of luck? Should we find other platforms to use (Colab Pro, etc.) or can we expect Kaggle to get it together and stay up-to-date?

### To Reproduce

Literally, try to do anything and realize that everything is out of date.

### Expected behaviour

Google Colab but on Kaggle

### Additional context

Other threads have been created on this topic... and lots of Github issues pertain to this
* See [here](https://www.kaggle.com/discussions/product-feedback/296467)

**Comment by darien-schettler** [comment] 2022-08-02 14:33
A potential solution could be to create the ability to select different docker images beyond 'original' and 'newest'. This could prevent the bloat to some degree and could allow for faster development?

**Comment by Philmod** [comment] 2022-08-02 14:38
Duplicate of https://github.com/Kaggle/docker-python/issues/1114

**Closed by Philmod** 2022-08-02 14:38 UTC
Labels: bug, help wanted

**Comment by darien-schettler** [comment] 2022-08-02 14:47
How is this a duplicate? It's similar I grant you... but it's not just about TF and Torch. It's about everything. Also that other thread was left dead for 3 months!

**Comment by darien-schettler** [comment] 2022-08-04 14:58
Any update on this? Or on the other thread @Philmod ?
